application: jigon-148213
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.9"
  

inbound_services:
- warmup
  
handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: main.app